# Generated by Django 3.2.9 on 2021-11-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0008_ride_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='drop_ride',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
