# Generated by Django 3.2.9 on 2021-11-16 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0009_ride_drop_ride'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
