# Generated by Django 3.2.9 on 2021-11-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0010_auto_20211116_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='grade',
            field=models.CharField(choices=[('4', 'Advanced'), ('3', 'Intermediate'), ('2', 'Improver'), ('1', 'Beginner')], default='1', max_length=2),
        ),
    ]
