# Generated by Django 3.2.9 on 2021-11-24 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0012_auto_20211124_2128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grades',
            new_name='Grade',
        ),
    ]
