# Generated by Django 3.2.9 on 2021-11-24 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0013_rename_grades_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
