# Generated by Django 3.2.9 on 2021-11-15 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 11, 15, 19, 32, 43, 694650)),
        ),
    ]
