# Generated by Django 3.2.9 on 2021-11-16 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_auto_20211115_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='time',
        ),
    ]
